#--------------------------------------------------------------
# Vagrant file to run a simple multi VM along libvirt provider.
#
# Reference docs:
# 1 - https://github.com/vagrant-libvirt/vagrant-libvirt
# 2 - https://wiki.archlinux.org/title/Vagrant
# 3 - https://wiki.archlinux.org/title/Libvirt
# 4 - https://wiki.archlinux.org/title/KVM
# 5 - https://wiki.archlinux.org/title/QEMU
# 6 - https://roboxes.org
#--------------------------------------------------------------
Vagrant.configure("2") do |config|

  NodeCount = 2

  (1..NodeCount).each do |i|

    config.vm.define "machine#{i}" do |node|

      node.vm.box               = "generic/ubuntu2004"
      node.vm.box_check_update  = false
      node.vm.box_version       = "3.6.12"
      node.vm.hostname          = "machine#{i}.example.com"

      node.vm.network "private_network", ip: "172.16.16.10#{i}"

      node.vm.provider :libvirt do |v|
        v.memory  = 2048
        v.nested  = true
        v.cpus    = 2
      end

      node.vm.provision "file", source: "~/.ssh/vagrant.pub", destination: "/home/vagrant/.ssh/authorized_keys"

      node.vm.provision "shell" do |s| 
        s.inline = "mkdir -p /root/.ssh; cp /home/vagrant/.ssh/authorized_keys /root/.ssh/"
        s.privileged = true
      end 

    end

  end

end
