Vagrant.configure("2") do |config|
  
    # Configuration of the provider and its specs
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end

    # Ubuntu 18.04 image  
    config.vm.box = "ubuntu/groovy64"
    
    # Ubuntu 20.04 image  
    # config.vm.box = "ubuntu/focal64"

    # Ubuntu 21.04 image  
    # config.vm.box = "ubuntu/hirsute64"
  
    # Take ip from DHCP server
    config.vm.network "public_network"
  
    # Mount folder with the content of the Docker Compose
    config.vm.synced_folder "~/getup/inceres/outros/mapnik-r-container/", "/data/"

    # Mount folder with the content of SGI
    # config.vm.synced_folder "../apps/sgi", "/vagrant_data/sgi"
  
    # Install Docker on the first run
   config.vm.provision "docker" do |d|
   end
    
    # Install Docker Compose
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        # apt-get install -y docker-compose
        # apt-get install -y apache2
        # curl -sL https://deb.nodesource.com/setup_12.x -o nodesource_setup.sh
        # bash nodesource_setup.sh
        # apt-get install -y nodejs
        # npm install -g @angular/cli
        cp -r /data/ /home/vagrant/inceres/
        # cp -r /vagrant_data/docker/ docker
        # ng build --prod
    SHELL
end
