#--------------------------------------------------------------
# Vagrant file to run a simple VM along libvirt provider.
#
# Reference docs:
# 1 - https://github.com/vagrant-libvirt/vagrant-libvirt
# 2 - https://wiki.archlinux.org/title/Vagrant
# 3 - https://wiki.archlinux.org/title/Libvirt
# 4 - https://wiki.archlinux.org/title/KVM
# 5 - https://wiki.archlinux.org/title/QEMU
# 6 - https://roboxes.org
#--------------------------------------------------------------
Vagrant.configure("2") do |config|
    
    #----------------------------------------------------------
    # Configuration of the provider and its specs
    #----------------------------------------------------------
    config.vm.provider "libvirt" do |v|
        v.memory = 2048
        v.cpus = 2
    end

    #----------------------------------------------------------
    # Choosing ubuntu 18.04 as a VM
    #----------------------------------------------------------
    config.vm.box = "generic/ubuntu1804"
    
    #----------------------------------------------------------
    # Choosing ubuntu 20.04 as a VM
    #----------------------------------------------------------
    # config.vm.box = "generic/ubuntu2004"

    #----------------------------------------------------------
    # Network configuration
    #----------------------------------------------------------
    ## Setting hostname
    config.vm.hostname = "vagrant.local"

    ## Public network taking ip from DHCP server
    ## make sure to create the bridge interface
    config.vm.define :machine do |machine|
      machine.vm.network :public_network,
        :dev => "nm-bridge",
        :mode => "bridge",
        :type => "bridge"
    end

    ## Private network with DHCP
    # config.vm.network "private_network", type: "dhcp"

    ## Private network with a static ip
    # config.vm.network "private_network", ip: "192.168.50.4"

    ## Forward guest port to host
    # config.vm.network "forwarded_port", guest: 80, host: 8080

    #----------------------------------------------------------
    # Mount configurations
    #----------------------------------------------------------
    ## Mount local folder inside the VM
    # config.vm.synced_folder "/local-path", "/vm-path"

    #----------------------------------------------------------
    # Provisioning
    #----------------------------------------------------------
    ## Install Docker on the first run
    # config.vm.provision "docker" do |d|
    # end
    
    ## Run shell commands
    # config.vm.provision "shell", inline: <<-SHELL
    #     apt-get update
    #     # next command
    # SHELL
end
