#--------------------------------------------------------------
# Vagrant file to run a simple VM along libvirt provider.
#
# Reference docs:
# 1 - https://github.com/vagrant-libvirt/vagrant-libvirt
# 2 - https://wiki.archlinux.org/title/Vagrant
# 3 - https://wiki.archlinux.org/title/Libvirt
# 4 - https://wiki.archlinux.org/title/KVM
# 5 - https://wiki.archlinux.org/title/QEMU
# 6 - https://roboxes.org
#--------------------------------------------------------------

#--------------------------------------------------------------
#                           VARIABLES
#--------------------------------------------------------------

#VAGRANT_BOX         = "generic/ubuntu2204"
VAGRANT_BOX         = "generic/arch"
VAGRANT_BOX_VERSION = "4.3.6"
CPUS                = 2
MEMORY              = 2048
HOSTNAME            = "vagrant.local"

#--------------------------------------------------------------
#                          CONFIGURATION
#--------------------------------------------------------------

Vagrant.configure("2") do |config|
    
    #----------------------------------------------------------
    # Configuration of the provider and its specs
    #----------------------------------------------------------
    config.vm.provider "libvirt" do |v|
        v.memory = MEMORY
        v.cpus = CPUS
    end

    #----------------------------------------------------------
    # Choosing the box
    #----------------------------------------------------------
    config.vm.box         = VAGRANT_BOX
    config.vm.box_version = VAGRANT_BOX_VERSION

    #----------------------------------------------------------
    # Network configuration
    #----------------------------------------------------------
    ## Setting hostname
    config.vm.hostname = HOSTNAME

    ## Public network taking ip from DHCP server
    ## make sure to create the bridge interface
    # config.vm.define :machine do |machine|
    #   machine.vm.network :public_network,
    #     :dev => "nm-bridge",
    #     :mode => "bridge",
    #     :type => "bridge"
    # end

    ## Private network with DHCP
    # config.vm.network "private_network", type: "dhcp"

    ## Private network with a static ip
    config.vm.network "private_network", ip: "192.168.50.2"

    ## Forward guest port to host
    config.vm.network "forwarded_port", guest: 80, host: 8080

    #----------------------------------------------------------
    # Mount configurations
    #----------------------------------------------------------
    ## Mount local folder inside the VM
    # config.vm.synced_folder "/local-path", "/vm-path", type: "rsync"

    #----------------------------------------------------------
    # Provisioning
    #----------------------------------------------------------
    ## Install Docker on the first run
    # config.vm.provision "docker" do |d|
    # end
    
    ## Run shell commands
    # config.vm.provision "shell", inline: <<-SHELL
    #     apt-get update
    #     # next command
    # SHELL
end
